config_rewrite: replace
langcode: en
status: true
dependencies:
  config:
    - field.field.node.webform.body
    - field.field.node.webform.webform
    - node.type.webform
  module:
    - panelizer
    - text
    - user
    - webform
third_party_settings:
  panelizer:
    enable: false
    custom: false
    allow: false
    default: default
id: node.webform.default
targetEntityType: node
bundle: webform
mode: default
content:
  body:
    label: hidden
    type: text_default
    weight: 101
    settings: {  }
    third_party_settings: {  }
    region: content
  links:
    weight: 100
    region: content
    settings: {  }
    third_party_settings: {  }
  webform:
    weight: 102
    label: hidden
    settings:
      source_entity: true
    third_party_settings: {  }
    type: webform_entity_reference_entity_view
    region: content
hidden:
  langcode: true
