config_rewrite: replace
langcode: en
status: true
dependencies:
  config:
    - core.entity_view_mode.node.teaser
    - field.field.node.webform.body
    - field.field.node.webform.webform
    - node.type.webform
  module:
    - panelizer
    - text
    - user
third_party_settings:
  panelizer:
    enable: false
    custom: false
    allow: false
    default: default
id: node.webform.teaser
targetEntityType: node
bundle: webform
mode: teaser
content:
  body:
    label: hidden
    type: text_summary_or_trimmed
    weight: 101
    settings:
      trim_length: 600
    third_party_settings: {  }
    region: content
  links:
    weight: 100
    region: content
    settings: {  }
    third_party_settings: {  }
hidden:
  langcode: true
  webform: true
