<?php
use Drupal\Component\Utility\Html;

function tbs_cssimg_preprocess_entity_embed_container(&$variables) {  
  if (!empty($variables['attributes']['class'][1])) {
    $class_custom = $variables['attributes']['class'][1];
    unset($variables['attributes']['class'][1]);
    $html_string = $variables['children']->__toString();
    $DOM_object = Html::load($html_string);
    foreach ($DOM_object->getElementsByTagName('img') as $img) {      
      $class = $img->getAttribute('class');
      if (!empty($class)) {
        $img->setAttribute('class', $class . ' ' . $class_custom);
      } else {
        $img->setAttribute('class', $class_custom);
      }
    }    
    $html_string = Html::serialize($DOM_object);
    $variables['children'] = $variables['children']->create($html_string);
  }
}