<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Url;

/**
 * Implements hook_migrate_moderation_sidebar_alter
 *
 * @param array $build
 *   The render array for the sidebar.
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *   The default or latest revision of an entity being moderated.
 *
 * @see \Drupal\moderation_sidebar\Controller\ModerationSidebarController::sideBar()
 */
function openplus_migrate_moderation_sidebar_alter(array &$build, \Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity->getEntityTypeId() == 'node') {
    $build['migrate_info'] = views_embed_view('migation_information', 'block_1', $entity->id());
    unset($build['actions']);
  }
}

function openplus_migrate_entity_operation_alter(array &$operations, \Drupal\Core\Entity\EntityInterface $entity) {
  // Add export link for migration groups
  if ($entity->getEntityTypeId() == 'migration_group') {
    $options = array('attributes' => array('title' => t('Export entire migration group.'), 'target' => '_blank'));
    $operations['export'] = array(
      'title' => t('Export migrations'),
      'weight' => 1,
      'url' => Url::fromRoute('entity.migration.export', ['migration_group' => $entity->id()]),
    );
  }
}
