name: Configuration Rewrite
type: module
description: Changes configuration YAML from config/install|optional with YAML from config/rewrite.
# core: 8.x
package: Configuration

# Information added by Drupal.org packaging script on 2017-05-22
version: '8.x-1.1'
core: '8.x'
project: 'config_rewrite'
datestamp: 1495478286
