<?php

/**
 * @file
 * Primary module hooks for CodeMirror editor module.
 */

/**
 * Implements hook_library_info_build().
 */
function codemirror_editor_library_info_build() {
  $library_builder = \Drupal::service('codemirror_editor.library_builder');
  return [
    'codemirror' => $library_builder->build(),
  ];
}

/**
 * Implements hook_js_settings_build().
 */
function codemirror_editor_js_settings_build(array &$settings) {
  if (isset($settings['codeMirrorEditor'])) {
    $buttons_path = drupal_get_path('module', 'codemirror_editor') . '/images/buttons.svg';
    $settings['codeMirrorEditor']['buttonsBaseUrl'] = file_create_url($buttons_path);
    $config = \Drupal::config('codemirror_editor.settings');
    $settings['codeMirrorEditor']['theme'] = $config->get('theme');
  }
  if (isset($settings['codeMirrorFormatter'])) {
    $config = \Drupal::config('codemirror_editor.settings');
    $settings['codeMirrorFormatter']['theme'] = $config->get('theme');
  }
}

/**
 * Implements hook_element_info_alter().
 */
function codemirror_editor_element_info_alter(array &$info) {
  $info['textarea']['#pre_render'][] = 'codemirror_editor_pre_render_textarea';
}

/**
 * Enables CodeMirror editor for a textarea.
 *
 * @param array $element
 *   An associative array containing the properties of the textarea.
 *
 * @return array
 *   The modified textarea element.
 */
function codemirror_editor_pre_render_textarea(array $element) {
  if (isset($element['#codemirror'])) {
    @trigger_error('Attaching CodeMirror to textareas directly is deprecated. Use #type codemirror instead.', E_USER_DEPRECATED);
    $element['#attributes']['data-codemirror'] = json_encode($element['#codemirror']);
    $element['#attached']['library'][] = 'codemirror_editor/editor';
  }
  return $element;
}

/**
 * Loads CodeMirror language modes.
 *
 * @return array
 *   The definitions of CodeMirror language modes.
 *
 * @deprecated Use
 *   Drupal\codemirror_editor\CodemirrorModeManagerInterface::getDefinitions()
 *   instead.
 */
function codemirror_editor_load_modes() {
  @trigger_error('codemirror_editor_load_modes() is deprecated. Use Drupal\codemirror_editor\CodemirrorModeManagerInterface::getDefinitions() instead', E_USER_DEPRECATED);
  return Drupal::service('plugin.manager.codemirror_mode')->getDefinitions();
}

/**
 * Normalizes language mode.
 *
 * @param string $mode
 *   Language mode to normalize.
 *
 * @return string
 *   Normalized language mode.
 *
 * @deprecated Use
 *   Drupal\codemirror_editor\CodemirrorModeManagerInterface::normalizeMode()
 *   instead.
 */
function codemirror_editor_normalize_mode($mode) {
  @trigger_error('codemirror_editor_load_modes() is deprecated. Use Drupal\codemirror_editor\CodemirrorModeManagerInterface::normalizeMode() instead', E_USER_DEPRECATED);
  return Drupal::service('plugin.manager.codemirror_mode')->normalizeMode($mode);
}
