config_rewrite: replace
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_blog_tags
    - node.type.blog_post
    - taxonomy.vocabulary.blog_freetags
id: node.blog_post.field_blog_tags
field_name: field_blog_tags
entity_type: node
bundle: blog_post
label: 'Blog tags'
description: 'Tags to help categorize blog post.'
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings:
  handler: 'default:taxonomy_term'
  handler_settings:
    target_bundles:
      blog_freetags: blog_freetags
    sort:
      field: _none
    auto_create: true
    auto_create_bundle: ''
field_type: entity_reference
