config_rewrite: replace
langcode: en
status: true
dependencies:
  module:
    - content_moderation
    - menu_ui
third_party_settings:
  menu_ui:
    available_menus: {  }
    parent: 'main:'
  lightning_workflow:
    workflow: editorial
name: 'Blog post'
type: blog_post
description: 'Use for multi-user blogs. Every user gets a personal blog.'
help: ''
new_revision: true
preview_mode: 0
display_submitted: false
