ckeditor_templates_ui.ckeditor_template.*:
  type: config_entity
  label: 'Ckeditor template'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Title'
    image:
      type: string
      label: 'Image'
    description:
      type: label
      label: 'Description'
    html:
      mapping:
        value:
          type: text
          label: 'Body'
        format:
          type: string
          label: 'Text format'
    weight:
      type: integer
      label: 'Weight'
