wxt_library.settings:
  type: config_object
  label: 'WxT Bootstrap Settings'
  mapping:
    theme:
      type: mapping
      label: 'Theme'
      mapping:
        visibility:
          type: integer
          label: 'Theme Visibility'
        themes:
          type: sequence
          label: 'Themes'
          sequence:
            type: string
            label: 'Themes'
    url:
      type: mapping
      label: 'URL'
      mapping:
        visibility:
          type: integer
          label: 'URL Visibility'
        pages:
          type: sequence
          label: 'Pages'
          sequence:
            type: string
            label: 'Pages'
    minimized:
      type: mapping
      label: 'Minimized'
      mapping:
        options:
          type: integer
          label: 'Minimized'
    files:
      type: mapping
      label: 'Files'
      mapping:
        types:
          type: sequence
          label: 'Types'
          sequence:
            type: string
            label: 'Types'
    wxt:
      type: mapping
      label: 'URL'
      mapping:
        theme:
          type: string
          label: 'WxT Theme'
