config_rewrite: replace
langcode: en
status: true
dependencies:
  module:
    - content_moderation
    - menu_ui
third_party_settings:
  menu_ui:
    available_menus:
      - sidebar
    parent: 'sidebar:'
  lightning_workflow:
    workflow: editorial
name: 'Basic page'
type: page
description: 'Use <em>basic pages</em> for your static content, such as an ''About us'' page.'
help: ''
new_revision: false
preview_mode: 1
display_submitted: false
