config_rewrite: replace
access_key: ''
secret_key: ''
use_path_style_endpoint: true
use_instance_profile: false
credentials_file: ''
bucket: d8-govcloud-ca
region: us-east-1
use_cname: true
use_customhost: true
hostname: 'minio:9000'
domain: stcdrupal.blob.core.windows.net/d8-govcloud-ca
cache_control_header: ''
encryption: ''
use_https: false
ignore_cache: false
redirect_styles_ttl: 0
no_rewrite_cssjs: false
root_folder: ''
public_folder: public
private_folder: private
presigned_urls: ''
saveas: ''
torrents: ''
